version: "3.9"

<<<<<<< HEAD
x-airflow-common: &airflow-common
  build:
    context: ..
    dockerfile: docker/Dockerfile.airflow
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__WEBSERVER__SECRET_KEY: "super_secret_airflow_key"
    AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
    AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
    PYTHONPATH: /opt/airflow/src
  volumes:
    - ../dags:/opt/airflow/dags
    - ../src:/opt/airflow/src
    - ../data:/opt/airflow/data
    - ../logs:/opt/airflow/logs
    - ~/.aws:/home/airflow/.aws
    - ../.env:/opt/airflow/.env
  depends_on:
    - postgres

services:

  postgres:
    image: postgres:15
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname admin
      --lastname user
      --role Admin
      --email admin@email.com
      "

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    restart: always
    command: webserver
    ports:
      - "8080:8080"
    env_file:
      - ../.env

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    restart: always
    command: scheduler

volumes:
  postgres_data:
=======
services:
  elt:
    container_name: elt_pipeline
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=sa-east-1
>>>>>>> 7b1d72ea7b5f713b66d843d3764b88cf2dbb4da2
